# backup.config.sh
COMPOSE_FILE="docker-compose.prod.yml"
POSTGRES_CONTAINER="uzol21_postgres_prod"
REDIS_CONTAINER="uzol21_redis_prod"
BACKUP_DIR="./backups"
RETENTION_DAYS=7
RETENTION_WEEKS=4

# Voliteľné nastavenia
BACKUP_REDIS=false
BACKUP_FILES=true
BACKUP_ENV=true

# Vzdialené úložisko - AWS S3
REMOTE_STORAGE_TYPE="s3"
REMOTE_STORAGE_PATH="s3://uzol21/backups"
AWS_ACCESS_KEY_ID="AKIARWF4Y7Z2GMXJ4E44"
AWS_SECRET_ACCESS_KEY="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"