import type { RouteRecordRaw } from 'vue-router';

/** Invoicing child routes (mounted under InvoicingEvoluLayout). */
export const invoicingRoutes: RouteRecordRaw[] = [
    {
        path: '',
        name: 'invoicing',
        component: () => import('../pages/invoicing/Index.vue'),
        meta: { requiresAuth: true, titleKey: 'invoicing.title' },
    },
    {
        path: 'companies/new',
        name: 'invoicing-company-new',
        component: () => import('../pages/invoicing/CompanyForm.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: 'companies/:companyId',
        name: 'invoicing-company',
        component: () => import('../pages/invoicing/CompanyShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'tools' },
    },
    {
        path: 'companies/:companyId/app',
        name: 'invoicing-company-app',
        component: () => import('../pages/invoicing/CompanyShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'tools' },
    },
    {
        path: 'companies/:companyId/app/emails',
        name: 'invoicing-company-app-emails',
        component: () => import('../pages/invoicing/CompanyShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'tools' },
    },
    {
        path: 'companies/:companyId/app/series',
        name: 'invoicing-company-app-series',
        component: () => import('../pages/invoicing/CompanyShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'tools' },
    },
    {
        path: 'companies/:companyId/import',
        name: 'invoicing-company-import',
        component: () => import('../pages/invoicing/DocumentImport.vue'),
        meta: { requiresAuth: true, invoicingSection: 'tools' },
    },
    {
        path: 'companies/:companyId/payments',
        name: 'invoicing-payments',
        component: () => import('../pages/invoicing/CompanyPayments.vue'),
        meta: { requiresAuth: true, invoicingSection: 'payments' },
    },
    {
        path: 'companies/:companyId/contacts',
        name: 'invoicing-contacts',
        component: () => import('../pages/invoicing/Contacts.vue'),
        meta: { requiresAuth: true, invoicingSection: 'contacts' },
    },
    {
        path: 'companies/:companyId/stock',
        name: 'invoicing-stock',
        component: () => import('../pages/invoicing/StockItems.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/stock/new',
        name: 'invoicing-stock-new',
        component: () => import('../pages/invoicing/StockItemForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/stock/:itemId',
        name: 'invoicing-stock-edit',
        component: () => import('../pages/invoicing/StockItemForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/warehouses',
        name: 'invoicing-warehouses',
        component: () => import('../pages/invoicing/Warehouses.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/warehouses/new',
        name: 'invoicing-warehouse-new',
        component: () => import('../pages/invoicing/WarehouseForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/warehouses/:warehouseId',
        name: 'invoicing-warehouse-edit',
        component: () => import('../pages/invoicing/WarehouseForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'stock' },
    },
    {
        path: 'companies/:companyId/contacts/new',
        name: 'invoicing-contact-new',
        component: () => import('../pages/invoicing/ContactForm.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: 'companies/:companyId/contacts/:contactId/edit',
        name: 'invoicing-contact-edit',
        component: () => import('../pages/invoicing/ContactForm.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: 'companies/:companyId/contacts/:contactId',
        name: 'invoicing-contact-show',
        component: () => import('../pages/invoicing/ContactShow.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: 'companies/:companyId/invoices',
        name: 'invoicing-invoices',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'invoice' },
    },
    {
        path: 'companies/:companyId/proformas',
        name: 'invoicing-proformas',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'proforma' },
    },
    {
        path: 'companies/:companyId/delivery-notes',
        name: 'invoicing-delivery-notes',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'delivery_note' },
    },
    {
        path: 'companies/:companyId/orders',
        name: 'invoicing-orders',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'order_received' },
    },
    {
        path: 'companies/:companyId/quotes',
        name: 'invoicing-quotes',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'quote' },
    },
    {
        path: 'companies/:companyId/recurring',
        name: 'invoicing-recurring',
        component: () => import('../pages/invoicing/RecurringProfiles.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'recurring' },
    },
    {
        path: 'companies/:companyId/recurring/new',
        name: 'invoicing-recurring-new',
        component: () => import('../pages/invoicing/RecurringProfileForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'recurring' },
    },
    {
        path: 'companies/:companyId/recurring/:profileId/edit',
        name: 'invoicing-recurring-edit',
        component: () => import('../pages/invoicing/RecurringProfileForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'recurring' },
    },
    {
        path: 'companies/:companyId/credit-notes',
        name: 'invoicing-credit-notes',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'credit_note' },
    },
    {
        path: 'companies/:companyId/drafts',
        name: 'invoicing-drafts',
        component: () => import('../pages/invoicing/Invoices.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'drafts' },
    },
    {
        path: 'companies/:companyId/expenses',
        name: 'invoicing-expenses',
        component: () => import('../pages/invoicing/Expenses.vue'),
        meta: { requiresAuth: true, invoicingSection: 'expenses' },
    },
    {
        path: 'companies/:companyId/expenses/new',
        name: 'invoicing-expense-new',
        component: () => import('../pages/invoicing/ExpenseForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'expenses' },
    },
    {
        path: 'companies/:companyId/expenses/:expenseId',
        name: 'invoicing-expense-show',
        component: () => import('../pages/invoicing/ExpenseShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'expenses' },
    },
    {
        path: 'companies/:companyId/expenses/:expenseId/edit',
        name: 'invoicing-expense-edit',
        component: () => import('../pages/invoicing/ExpenseForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'expenses' },
    },
    {
        path: 'companies/:companyId/proformas/new',
        name: 'invoicing-proforma-new',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'proforma' },
    },
    {
        path: 'companies/:companyId/proformas/:documentId',
        name: 'invoicing-proforma-show',
        component: () => import('../pages/invoicing/InvoiceShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'proforma' },
    },
    {
        path: 'companies/:companyId/proformas/:documentId/edit',
        name: 'invoicing-proforma-edit',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'proforma' },
    },
    {
        path: 'companies/:companyId/quotes/new',
        name: 'invoicing-quote-new',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'quote' },
    },
    {
        path: 'companies/:companyId/quotes/:documentId',
        name: 'invoicing-quote-show',
        component: () => import('../pages/invoicing/InvoiceShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'quote' },
    },
    {
        path: 'companies/:companyId/quotes/:documentId/edit',
        name: 'invoicing-quote-edit',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'quote' },
    },
    {
        path: 'companies/:companyId/credit-notes/new',
        name: 'invoicing-credit-note-new',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'credit_note' },
    },
    {
        path: 'companies/:companyId/credit-notes/:documentId',
        name: 'invoicing-credit-note-show',
        component: () => import('../pages/invoicing/InvoiceShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'credit_note' },
    },
    {
        path: 'companies/:companyId/credit-notes/:documentId/edit',
        name: 'invoicing-credit-note-edit',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'credit_note' },
    },
    {
        path: 'companies/:companyId/invoices/new',
        name: 'invoicing-invoice-new',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'invoice' },
    },
    {
        path: 'companies/:companyId/invoices/:documentId',
        name: 'invoicing-invoice-show',
        component: () => import('../pages/invoicing/InvoiceShow.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'invoice' },
    },
    {
        path: 'companies/:companyId/invoices/:documentId/edit',
        name: 'invoicing-invoice-edit',
        component: () => import('../pages/invoicing/InvoiceForm.vue'),
        meta: { requiresAuth: true, invoicingSection: 'documents', documentKind: 'invoice' },
    }
];
